### ISSUE TITLE
NoSuchMethodError - PictureExportFormat

### ISSUE THREAD

**Issue by jackjt8** [chunky-dev/chunky-denoiser#36] opened 2022-10-16 13:35 UTC
`.tiff` - Render is denoised correctly once target SPP is reached and exported as `.tiff`

Enable `Save beauty pass` - We get the following error once target SPP is reached and it breaks Chunky (UI functions but no renderer can be reset/used):

```
Unchecked exception in render manager.
java.lang.NoSuchMethodError: 'void se.llbit.chunky.renderer.scene.Scene.saveFrame(java.io.File, se.llbit.chunky.renderer.export.PictureExportFormat, se.llbit.util.TaskTracker, int)'
	at de.lemaik.chunky.denoiser.DenoisedPathTracingRenderer.render(DenoisedPathTracingRenderer.java:90)
	at se.llbit.chunky.renderer.DefaultRenderManager.run(DefaultRenderManager.java:313)
```

**Comment by leMaik** [comment] 2022-10-31 16:46
Duplicate of #32

**Closed by leMaik** 2022-10-31 16:46 UTC
